- name: Download Python 3.8.9
  shell: |
    wget http://datalake-repo:8080/downloads/python/3.8.9/Python-3.8.9.tgz
    tar xvf Python-3.8.9.tgz
- name: Install Python 3.8.9
  shell: |
    cd Python-3.8*
    ./configure --enable-optimizations
    make altinstall
- name: Copy pip config file
  ansible.builtin.copy:
    src: template/pip.conf
    dest: /root/.pip/pip.conf
    owner: root
    group: root
    mode: '0777'
- name: Create a Python3 Symbolic Link
  shell: sudo ln -s /usr/local/bin/python3.8 /bin/python3
  ignore_errors: yes
- name: Upgrade Pip
  shell: python3 -m pip install --upgrade pip
- name: Check Python3 version
  shell: |
    python3 -V
    python3 -m pip --version
  register: result

- debug: var=result.stdout_lines
